services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z 

  ml:
    build:
      context: ./support-hints-agent-system
      dockerfile: Dockerfile
    container_name: ml-agent-container
    restart: unless-stopped
    ports:
      - "8004:8004"
    environment:
      - QDRANT_URL=http://qdrant:6333
    env_file:
      - .env
    depends_on:
      - qdrant