global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 't1-minsk'
    env: 'production'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 't1-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8001']
        labels:
          service: 'backend-api'

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
        labels:
          service: 'kafka'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
        labels:
          service: 'redis'

  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
        labels:
          service: 'mongodb'

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - "alert_rules.yml"

